# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: WebDriverIO CI

on:
  push:
    branches: [ main ]

jobs:
  web_test:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 17.x
        cache: 'npm'
    - name: setup chrome
      uses: browser-actions/setup-chrome@latest
      with:
        chrome-version: stable
    - name: Run sanity test on local
      run: |
        npm ci
        npm run test:local -- --suite sanity
    - name: Generate reports
      run: npx allure generate --clean allure-results
    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      if: ${{ always() }}
      with:
        name: web_test
        path: allure-reports
